# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(max_length=100)),
                ('street2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=100)),
                ('home_num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('job', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonChurch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.CharField(max_length=100)),
                ('vehicle_license', models.CharField(max_length=100)),
                ('baptized_date', models.CharField(max_length=100)),
                ('baptized_church', models.CharField(max_length=100)),
                ('infant_baptized_church', models.CharField(max_length=100)),
                ('infant_baptized_date', models.CharField(max_length=100)),
                ('person_status', models.CharField(max_length=100)),
                ('position_type', models.CharField(max_length=100)),
                ('last_church_name', models.CharField(max_length=100)),
                ('last_church_leader', models.CharField(max_length=100)),
                ('friends_in_church', models.CharField(max_length=100)),
                ('volunteer_experience', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcomer.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_fname', models.CharField(max_length=100)),
                ('k_lname', models.CharField(max_length=100)),
                ('e_fname', models.CharField(max_length=100)),
                ('e_lname', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcomer.Person')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcomer.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcomer.Person'),
        ),
    ]
